SUPABASE_URL = "https://mzgudrvnimulewxwglms.supabase.co"
SUPABASE_KEY = "sb_publishable_0e-wfXAE67BGI8ahMk-AoQ_jphdbY_5"
[email]
sender = "nsmartonline8@gmail.com"
password = "ozshzejwxoaiojyc"
recipient = "nsmartonline8@gmail.com"
smtp_server = "smtp.gmail.com"
smtp_port = 465
